// Code generated by apicli. DO NOT EDIT.

package main

import (
    "github.com/hnhuaxi/appcli"
)

var Injects = map[string]interface{} {
	// "$actionFunc": appcli.ActionFunc,
	"$funcs": appcli.BuiltinObjects,
	"$injects": appcli.Injects,
	"$loadPackages": appcli.LoadPackages,
	"$newObject": appcli.NewObject,
	"$newPlainEncoder": appcli.NewPlainEncoder,
	"$quote": appcli.Quote,
	"$registerCreate": appcli.RegisterCreate,
	"$version": appcli.Version,
	"App": "$$ClassApp",
	"Command": "$$ClassCommand",
	"Flag": "$$ClassFlag",
	"Inject": "$$ClassInject",
	"InjectContext": "$$ClassInjectContext",
	"Match": "$$ClassMatch",
	"Output": "$$ClassOutput",
	"Program": "$$ClassProgram", 
}

func init() {
    appcli.Injects(Injects)
	appcli.RegisterCreate("$$ClassApp", appcli.App{})
	appcli.RegisterCreate("$$ClassCommand", appcli.Command{})
	appcli.RegisterCreate("$$ClassFlag", appcli.Flag{})
	appcli.RegisterCreate("$$ClassInject", appcli.Inject{})
	appcli.RegisterCreate("$$ClassInjectContext", appcli.InjectContext{})
	appcli.RegisterCreate("$$ClassMatch", appcli.Match{})
	appcli.RegisterCreate("$$ClassOutput", appcli.Output{})
	appcli.RegisterCreate("$$ClassProgram", appcli.Program{})
}